username = input("Введите имя пользователя: ")
resulf = username.upper()
print("Username:", resulf)
title = input("Введите заголовок заметки: ")
print('Title: ', title)
content = input("Введите описание заметки: ")
print('Content: ', content)
statis = input("Введите статус заметки:  ")
print('Statis: ', statis)
created_data = input("Введите дату создания заметки в формате-'день.месяц.год': ")
print('Created_data: ',created_data )
issue_date = input("Введите дату истечения заметки в формате-'день.месяц.год': ")
print('Issue_date: ', issue_date)

